channels = "../../docker/channels.toml"

[exp]
  log_level = "debug"
  nats = "nats://127.0.0.1:4222"
  port = "8170"

[mqtt]
  ca = "ca.crt"
  cert = "thing.crt"
  channel = "4c66a785-1900-4844-8caa-56fb8cfd61eb"
  mtls = "false"
  password = "ac6b57e0-9b70-45d6-94c8-e67ac9086165"
  priv_key = "thing.key"
  retain = "false"
  skip_tls_ver = "false"
  url = "tcp://localhost:18831"
  username = "4a437f46-da7b-4469-96b7-be754b5e8d36"
